/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SanPham;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SanPhamDiaLog extends javax.swing.JDialog {

    static int id = 0;
    SanPhamDAO daosp = new SanPhamDAO();

    /**
     * Creates new form SanPhamDiaLog
     */
    public SanPhamDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        filldata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmasanpham = new javax.swing.JTextField();
        txtmota = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txttensanpham = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabsanpham = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SẢN PHẨM");

        jLabel2.setText("MÃ SẢN PHẨM");

        jLabel3.setText("MÔ TẢ");

        jLabel4.setText("SỐ LƯỢNG");

        jLabel5.setText("ĐƠN GIÁ");

        jLabel6.setText("TÊN SẢN PHẨM");

        tabsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SẢN PHẨM", "MÔ TẢ", "SỐ LƯỢNG", "ĐƠN GIÁ", "TÊN SẢN PHẨM", "THÀNH TIỀN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabsanphamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabsanphamMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabsanpham);

        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("SỬA");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnmoi.setText("MỚI");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnxoa.setText("XÓA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnexit.setText("THOÁT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnsua))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnthem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnmoi)
                                            .addComponent(btnxoa)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnFirst)
                                .addGap(30, 30, 30)
                                .addComponent(btnBack)
                                .addGap(30, 30, 30)
                                .addComponent(btnNext)
                                .addGap(34, 34, 34)
                                .addComponent(btnLast)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnexit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnFirst)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(34, 34, 34)
                .addComponent(btnexit)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void seret() {
        txtdongia.setText("");
        txtmasanpham.setText("");
        txtmota.setText("");
        txtsoluong.setText("");
        txttensanpham.setText("");
    }
    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        seret();
    }//GEN-LAST:event_btnmoiActionPerformed
    public SanPham getModel() {
        SanPham sp = new SanPham();
        sp.setDonGia(Double.parseDouble(txtdongia.getText()));
        sp.setMaSP(Integer.parseInt(txtmasanpham.getText()));
        sp.setMoTa(txtmota.getText());
        sp.setSoLuong(Integer.parseInt(txtsoluong.getText()));
        sp.setTenSP(txttensanpham.getText());
        return sp;
    }

    public void filldata() {
        DefaultTableModel model = (DefaultTableModel) tabsanpham.getModel();
        model.setRowCount(0);
        for (SanPham sp : daosp.getAllSanPham()) {
            Object rowdata[] = new Object[6];
            rowdata[0] = sp.getMaSP();
            rowdata[1] = sp.getMoTa();
            rowdata[2] = sp.getSoLuong();
            rowdata[3] = sp.getDonGia();
            rowdata[4] = sp.getTenSP();
            rowdata[5] = sp.getSoLuong() * sp.getDonGia();
            model.addRow(rowdata);
        }
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (txtmasanpham.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "YÊU CẦU BẠN NHẬP ĐẦY ĐỦ");
        } else {
            SanPham sp = getModel();
            if (daosp.add(sp) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "bạn thêm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "bạn thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtmasanpham.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "YÊU CẦU BẠN NHẬP ĐẦY ĐỦ");
        } else {
            SanPham sp = getModel();
            if (daosp.edit(sp) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "bạn edit thành công");
            } else {
                JOptionPane.showMessageDialog(this, "bạn edit thất bại");
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmasanpham.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "YÊU CẦU BẠN NHẬP ĐẦY ĐỦ");
        } else {
            SanPham sp = getModel();
            if (daosp.dell(sp) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "bạn xóa thành công");
            } else {
                JOptionPane.showMessageDialog(this, "bạn xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tabsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsanphamMouseClicked
        // TODO add your handling code here:
        SanPham sp = new SanPham();
        int rowdata = tabsanpham.rowAtPoint(evt.getPoint());
        txtdongia.setText(tabsanpham.getValueAt(rowdata, 3).toString());
        txtmasanpham.setText(tabsanpham.getValueAt(rowdata, 0).toString());
        txtmota.setText(tabsanpham.getValueAt(rowdata, 1).toString());
        txtsoluong.setText(tabsanpham.getValueAt(rowdata, 2).toString());
        txttensanpham.setText(tabsanpham.getValueAt(rowdata, 4).toString());
    }//GEN-LAST:event_tabsanphamMouseClicked

    private void tabsanphamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsanphamMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int rowdata = tabsanpham.rowAtPoint(evt.getPoint());
            txtdongia.setText(tabsanpham.getValueAt(rowdata, 3).toString());
            txtmasanpham.setText(tabsanpham.getValueAt(rowdata, 0).toString());
            txtmota.setText(tabsanpham.getValueAt(rowdata, 1).toString());
            txtsoluong.setText(tabsanpham.getValueAt(rowdata, 2).toString());
            txttensanpham.setText(tabsanpham.getValueAt(rowdata, 4).toString());
        }
    }//GEN-LAST:event_tabsanphamMousePressed
    public void setModel(SanPham sp) {
        txtdongia.setText(Double.toString(sp.getDonGia()));
        txtmasanpham.setText(Integer.toString(sp.getMaSP()));
        txtmota.setText(sp.getMoTa());
        txtsoluong.setText(Integer.toString(sp.getSoLuong()));
        txttensanpham.setText(sp.getTenSP());
    }
    public SanPham getSanPhamNHAtPosition(int pos){
    SanPham sp = new SanPham();
    sp.setMaSP(Integer.parseInt(tabsanpham.getValueAt(pos, 0).toString()));
    sp.setMoTa((tabsanpham.getValueAt(pos, 1).toString()));
    sp.setSoLuong(Integer.parseInt(tabsanpham.getValueAt(pos, 2).toString()));
    sp.setDonGia(Double.parseDouble(tabsanpham.getValueAt(pos, 3).toString()));
    sp.setTenSP((tabsanpham.getValueAt(pos, 4).toString()));
    return sp;
    }
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        id=0;
        SanPham sp =getSanPhamNHAtPosition(id);
        setModel(sp);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        id--;
        if (id<=0) {
            id=0;
        }
         SanPham sp =getSanPhamNHAtPosition(id);
        setModel(sp);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        id++;
        if (id>=daosp.getAllSanPham().size()-1) {
            id=daosp.getAllSanPham().size()-1;
        }
        SanPham sp =getSanPhamNHAtPosition(id);
        setModel(sp);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        id = daosp.getAllSanPham().size()-1;
        SanPham sp =getSanPhamNHAtPosition(id);
        setModel(sp);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPhamDiaLog dialog = new SanPhamDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabsanpham;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmasanpham;
    private javax.swing.JTextField txtmota;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttensanpham;
    // End of variables declaration//GEN-END:variables
}
