package models;
// Generated May 6, 2020 8:46:36 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,schema="dbo"
    ,catalog="Products"
)
public class Products  implements java.io.Serializable {


     private String masp;
     private String tensp;
     private Date ngaynhap;
     private float giatien;
     private Integer soluong;
   

    

     
    public Products() {
    }

	
    public Products(String masp) {
        this.masp = masp;
    }
    public Products(String masp, String tensp, Date ngaynhap, float giatien, Integer soluong) {
       this.masp = masp;
       this.tensp = tensp;
       this.ngaynhap = ngaynhap;
       this.giatien = giatien;
       this.soluong = soluong;
    }
   
     @Id 

    
    @Column(name="masp", unique=true, nullable=false)
    public Serializable getMasp() {
        return this.masp;
    }
    
    public void setMasp(String masp) {
        this.masp = masp;
    }

    
    @Column(name="tensp")
    public Serializable getTensp() {
        return this.tensp;
    }
    
    public void setTensp(String tensp) {
        this.tensp = tensp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaynhap", length=10)
    public Date getNgaynhap() {
        return this.ngaynhap;
    }
    
    public void setNgaynhap(Date ngaynhap) {
        this.ngaynhap = ngaynhap;
    }

    
    @Column(name="giatien", precision=53, scale=0)
    public Float getGiatien() {
        return this.giatien;
    }
    
    public void setGiatien(float giatien) {
        this.giatien = giatien;
    }

    
    @Column(name="soluong")
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }




}


