/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChuyennganhS;
import model.ChuyennganhSDAO;
import model.SachDAO;
import model.Sachfr;

/**
 *
 * @author trany
 */
public class FrSach extends javax.swing.JFrame {

    SachDAO daos = new SachDAO();
    public static ChuyennganhSDAO daocn = new ChuyennganhSDAO();
    SimpleDateFormat date_Format = new SimpleDateFormat("dd/MM/yyyy");
    static int position = 0;
    String strHinhanh = null;

    /**
     * Creates new form FrSach
     */
    public FrSach() {
        initComponents();
        getCombobox();
        setLocationRelativeTo(null);

    }

    public void getCombobox() {
        DefaultComboBoxModel<ChuyennganhS> model = (DefaultComboBoxModel) cbochuyenNganhs.getModel();
        model.removeAllElements();
        for (ChuyennganhS cn : daocn.getAllChuyenNganhS()) {
            model.addElement(cn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmSach = new javax.swing.JTextField();
        txttenSach = new javax.swing.JTextField();
        cbochuyenNganhs = new javax.swing.JComboBox<>();
        txtngayNhap = new javax.swing.JTextField();
        txtsoLuong = new javax.swing.JTextField();
        txtgiaBan = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        lblhinhanh = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        btnSAVE = new javax.swing.JButton();
        btnEDIT = new javax.swing.JButton();
        btnXOA = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbang = new javax.swing.JTable();
        lblstatus = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("SACH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MA SACH:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TEN SACH:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CHUYEN NGANH:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NGAY NHAP:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("SO LUONG:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("GIA BAN:");

        cbochuyenNganhs.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbochuyenNganhsPopupMenuWillBecomeVisible(evt);
            }
        });

        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        lblhinhanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblhinhanh.setText("LOGO");
        lblhinhanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblhinhanh.setMinimumSize(new java.awt.Dimension(200, 200));
        lblhinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhinhanhMouseClicked(evt);
            }
        });

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnSAVE.setText("SAVE");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnEDIT.setText("EDIT");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });

        btnXOA.setText("XOA");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnthoat.setText("EXIT");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        tbbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SÁCH", "TÊN SÁCH", "CHUYÊN NGÀNH", "NGÀY NHẬP", "SỐ LƯỢNG", "GIÁ BÁN", "THÀNH TIỀN", "HÌNH ẢNH"
            }
        ));
        tbbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbbang);

        lblstatus.setText("STATUS:");

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbochuyenNganhs, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCong))
                    .addComponent(txtngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmSach, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnADD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSAVE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXOA)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnFirst)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnLast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbochuyenNganhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCong)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtgiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnADD)
                            .addComponent(btnSAVE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEDIT)
                            .addComponent(btnXOA))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnBack)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstatus)
                    .addComponent(btnthoat)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        dispose();
    }//GEN-LAST:event_btnthoatActionPerformed

    public void reset() {
        txtmSach.setText("");
        txttenSach.setText("");
        cbochuyenNganhs.setSelectedItem(0);
        txtngayNhap.setText("");
        txtsoLuong.setText("");
        txtgiaBan.setText("");

//        lblhinhanh.setText("");
        lblhinhanh.setText("HINH ANH");
        lblhinhanh.setIcon(null);
        strHinhanh = null;

    }
    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnADDActionPerformed


    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        // TODO add your handling code here:
        if (validataF()) {
            try {
                Sachfr r = getModel();
                if (daos.add(r) > 0) {
                    JOptionPane.showMessageDialog(this, "BAN LUU THANH CONG");
                    filldata();
                }
            } catch (ParseException ex) {
                Logger.getLogger(FrSach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSAVEActionPerformed
    public Sachfr getModel() throws ParseException {
        Sachfr r = new Sachfr();
        r.setmSach(txtmSach.getText().trim());
        r.settSach(txttenSach.getText().trim());
        r.setChuyennganhS((ChuyennganhS) cbochuyenNganhs.getSelectedItem());
        r.setNgaynhap(date_Format.parse(txtngayNhap.getText().trim()));
        r.setGiaban(Double.parseDouble(txtgiaBan.getText().trim()));
        r.setSoluong(Integer.parseInt(txttenSach.getText().trim()));
        if (strHinhanh == null) {
            r.setHinhanh("NO AVATA");

        } else {
            r.setHinhanh(strHinhanh);
        }
        return r;
    }
//

    public boolean validataF() {
        if (txtmSach.getText().isEmpty() || txttenSach.getText().isEmpty() || txtngayNhap.getText().isEmpty() || txtgiaBan.getText().isEmpty()
                || txtsoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CAN NHAP THONG TIN DAY DU");
            return false;
        }
        int soluong = Integer.parseInt(txtsoLuong.getText());
        double giaban = Double.parseDouble(txtgiaBan.getText());
        if (soluong < 0) {
            JOptionPane.showMessageDialog(this, "YEU CAU NHAP LAI SO LUONH");
            txtsoLuong.setBackground(Color.red);
            return false;
        }
        if (giaban < 0) {
            JOptionPane.showMessageDialog(this, "YEU CAU NHAP LAI GIA BAN");
            txtgiaBan.setBackground(Color.red);
            return false;
        }
        return true;
    }
//

    public void filldata() {
        DefaultTableModel tb = (DefaultTableModel) tbbang.getModel();
        tb.setRowCount(0);//xoa bang
        for (Sachfr s : daos.getALLSACHFr()) {
            Object rowdata[] = new Object[8];
            rowdata[0] = s.getmSach();
            rowdata[1] = s.gettSach();
            rowdata[2] = s.getChuyennganhS();
            rowdata[3] = date_Format.format(s.getNgaynhap());
            rowdata[4] = s.getSoluong();
            rowdata[5] = s.getGiaban();
            rowdata[6] = s.getSoluong() * s.getGiaban();
            rowdata[7] = s.getHinhanh();
            tb.addRow(rowdata);
        }

    }

    //
    public void setModel(Sachfr r) {
        int rowdata = tbbang.getSelectedRow();
        txtmSach.setText(r.getmSach());
        txttenSach.setText(r.gettSach());
        cbochuyenNganhs.setSelectedItem(r.getChuyennganhS());
        txtngayNhap.setText(date_Format.format(r.getNgaynhap()));
        txtsoLuong.setText(r.getSoluong() + "");
        txtgiaBan.setText(r.getGiaban() + "");
        //hinh anh
        if (r.getHinhanh().equalsIgnoreCase("NO AVATA")) {
            lblhinhanh.setText("NO AVATA");
            lblhinhanh.setIcon(null);

        } else {
            lblhinhanh.setText("");
            ImageIcon micon = new ImageIcon(getClass().getResource("/images/" + tbbang.getValueAt(rowdata, 7).toString()));
            Image img = micon.getImage();
            img.getScaledInstance(lblhinhanh.getWidth(), lblhinhanh.getHeight(), 0);
            lblhinhanh.setIcon(micon);

        }

    }
    private void lblhinhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhinhanhMouseClicked
        try {
            JFileChooser fileChooser = new JFileChooser("D:\\Users\\trany\\Documents\\NetBeansProjects\\OntapthiP1\\build\\classes\\images");
            fileChooser.showOpenDialog(null);
            File file = fileChooser.getSelectedFile();
            Image img = ImageIO.read(file);
            strHinhanh = file.getName();
            lblhinhanh.setText("");
            int width = lblhinhanh.getWidth();
            int height = lblhinhanh.getHeight();
            lblhinhanh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (IOException ex) {
//            Logger.getLogger(FrSach.class.getName()).log(Level.SEVERE, null, ex);
System.out.println("Error:"+ex.toString());
        }


    }//GEN-LAST:event_lblhinhanhMouseClicked

    private void tbbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbangMouseClicked
        // TODO add your handling code here:
//do du lieu tu table len tren.
        int id = tbbang.rowAtPoint(evt.getPoint());
        String mSach = tbbang.getValueAt(id, 0).toString();
        Sachfr r = daos.getSachBYID(mSach);
        if (r == null) {
            return;
        }
        setModel(r);
        position = id;
    }//GEN-LAST:event_tbbangMouseClicked

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
        // TODO add your handling code here:
        if (txtmSach.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP MA DAY DU");
        } else {
            try {
                Sachfr r = getModel();
                if (daos.editS(r) > 0) {
                    lblstatus.setText("BAT DAU SUA LAI THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    filldata();
                } else {
                    lblstatus.setText("KHONG TIM THAY TEN DE SUA");
                    lblstatus.setForeground(Color.red);
                }
            } catch (ParseException ex) {
                System.out.println("EROOR" + ex.toString());
            }

        }


    }//GEN-LAST:event_btnEDITActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        // TODO add your handling code here:
        if (txtmSach.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP MA");
        } else {
            if (daos.delBYID(txtmSach.getText().trim()) > 0) {
                lblstatus.setText("BAN XOA THANH CONG");
                lblstatus.setForeground(Color.blue);
                filldata();
            } else {
                lblstatus.setText("KHONG TIM THAY NOI DUNG");
                lblstatus.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void cbochuyenNganhsPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbochuyenNganhsPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        getCombobox();
    }//GEN-LAST:event_cbochuyenNganhsPopupMenuWillBecomeVisible

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        DialongChuyenNganh cn = new DialongChuyenNganh(this, true);
        cn.setVisible(true);
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        position = 0;
        Sachfr s = daos.getSachfATPOINT(position);
        setModel(s);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        position = daos.count() - 1;
        Sachfr s = daos.getSachfATPOINT(position);
        setModel(s);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        position--;
        if (position <= 0) {
            position = 0;

        }
        Sachfr s = daos.getSachfATPOINT(position);
        setModel(s);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        position++;
        if (position >= daos.count() - 1) {
            position = daos.count() - 1;
        }
        Sachfr s = daos.getSachfATPOINT(position);
        setModel(s);

    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnXOA;
    private javax.swing.JButton btnthoat;
    private javax.swing.JComboBox<String> cbochuyenNganhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblhinhanh;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tbbang;
    private javax.swing.JTextField txtgiaBan;
    private javax.swing.JTextField txtmSach;
    private javax.swing.JTextField txtngayNhap;
    private javax.swing.JTextField txtsoLuong;
    private javax.swing.JTextField txttenSach;
    // End of variables declaration//GEN-END:variables
}
