/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaSwing;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trany
 */
public class FrQuanLyNV extends javax.swing.JFrame {

    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    QuanLyNVDAO dao = new QuanLyNVDAO();
    static int position = 0;

    /**
     * Creates new form FrQuanLyNV
     */
    public FrQuanLyNV() {
        initComponents();
        setLocationRelativeTo(null);
    }

    // phan combobox va filldata
    public void filldata() {
        DefaultTableModel tbmodel = (DefaultTableModel) tabbang.getModel();
        tbmodel.setRowCount(0);//xoa data trong table
        for (QuanLyNV nv : dao.getALLQuanLY()) {
            Object rowdata[] = new Object[5];
            rowdata[0] = nv.getMaNV();
            rowdata[1] = nv.getTenNV();
            //ngay sinh hien thi 
            rowdata[2] = date_format.format(nv.getNgaySinh());
            //gioi tinh hien thij nam/nu
            String gt = "Nu";
            if (nv.isGioiTinh()) {
                gt = "Nam";
            }
            rowdata[3] = gt;
            rowdata[4] = nv.getPhongBan();
            tbmodel.addRow(rowdata);
        }
    }

    //phan ADD
    public void seret() {
        txtmanv.setText("");
        txttennv.setText("");
        txtngaysinh.setText("");
        rdNam.setSelected(true);
        cboPhongban.setSelectedIndex(0);
    }
// Phan SAVE

    public QuanLyNV getModel() throws ParseException {
        QuanLyNV nv = new QuanLyNV();
        nv.setMaNV(txtmanv.getText());
        nv.setTenNV(txttennv.getText());
        nv.setNgaySinh(date_format.parse(txtngaysinh.getText()));
        boolean gt = false;
        if (rdNam.isSelected()) {
            gt = true;
        }
        nv.setGioiTinh(gt);
        nv.setPhongBan(cboPhongban.getSelectedItem().toString());
        return nv;
    }

    public boolean checkValidate() {
        if (txtmanv.getText().isEmpty()
                || txttennv.getText().isEmpty()
                || txtngaysinh.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public void setModel(QuanLyNV nv) {
        txtmanv.setText(nv.getMaNV());
        txttennv.setText(nv.getTenNV());
        txtngaysinh.setText(date_format.format(nv.getNgaySinh()));
        rdNam.setSelected(nv.isGioiTinh());
        rdNu.setSelected(!nv.isGioiTinh());
        cboPhongban.setSelectedItem(nv.getPhongBan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txttennv = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        cboPhongban = new javax.swing.JComboBox<>();
        btnfind = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();
        btnFrist = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabbang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("QUAN LY NHAN VIEN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MA NHAN VIEN:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("TEN NHAN VIEN:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("NGAY SINH:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("GIOI TINH:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PHONG BAN:");

        buttonGroup1.add(rdNam);
        rdNam.setText("NAM");

        buttonGroup1.add(rdNu);
        rdNu.setText("NU");

        cboPhongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GIAM DOC", "NHAN VIEN", "KE TOAN", "QUAN LY", " " }));

        btnfind.setText("FIND");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnxoa.setText("XOA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        lblCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCount.setText("COUNT:");

        btnFrist.setText("|<");
        btnFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFristActionPerformed(evt);
            }
        });

        btnback.setText("<<");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnthoat.setText("THOAT");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        lblstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstatus.setText("STATUS");

        tabbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MA NHAN VIEN", "TEN NHAN VIEN", "NGAY SINH", "GIOI TINH", "PHONG BAN"
            }
        ));
        tabbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabbang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCount)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdNam)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdNu))
                                            .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txttennv, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txtmanv)
                                            .addComponent(cboPhongban, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnfind)
                                            .addComponent(btnadd)
                                            .addComponent(btnsave)
                                            .addComponent(btnedit)
                                            .addComponent(btnxoa)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFrist)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnback)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNext)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLast)))))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblstatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnthoat))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdNam)
                    .addComponent(rdNu)
                    .addComponent(btnedit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrist)
                    .addComponent(btnback)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthoat)
                    .addComponent(lblstatus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        seret();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            try {
                QuanLyNV nv = getModel();
                if (dao.add(nv) > 0) {
                    JOptionPane.showMessageDialog(this, "BAN DA LUU THANH CONG");
                    lblstatus.setText("BAN DA LUU THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    lblCount.setText("COUNT:" + dao.count());
                    //cap nhat thanh cong load data len table
                    filldata();
                } else {
                    lblstatus.setText("BAN DA LUU KHONG THANH CONG");
                    lblstatus.setForeground(Color.red);
                }
            } catch (ParseException ex) {
                System.out.println("Error:" + ex.toString());;
            }

        } else {
            JOptionPane.showMessageDialog(this, "BAN LUU THAT BAI");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if (txtmanv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA CAP NHAT NHAN VIEN");

        } else {
            try {
                QuanLyNV nv = getModel();
                if (dao.edit(nv) > 0) {
                    lblstatus.setText("BAN DA CAP NHAT THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    filldata();
                } else {

                    lblstatus.setText("BAN KHONG TIM THAY");
                    lblstatus.setForeground(Color.red);
                }
            } catch (ParseException ex) {
                System.out.println("Error:" + ex.toString());;
            }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (dao.del(txtmanv.getText()) > 0) {
            JOptionPane.showMessageDialog(this, "BAN XOA THANH CONG");
            lblCount.setText("COUNT:" + dao.count());
            filldata();
        } else {
            lblstatus.setText("KHONG TIM THAY");
            lblstatus.setForeground(Color.red);

        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        if (txtmanv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP MA TIM KIEM ");
        } else {
            QuanLyNV nv = dao.findBYID(txtmanv.getText());
            if (nv != null) {
                setModel(nv);
            } else {
                lblstatus.setText("KHONG TIM THAY NHAN VIEN" + txtmanv.getText());
                lblstatus.setForeground(Color.red);
            }

        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFristActionPerformed
        // TODO add your handling code here:
        position = 0;
        setModel(dao.getOneQuanLyNVAtPosition(position));

    }//GEN-LAST:event_btnFristActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        position = dao.count() - 1;
        setModel(dao.getOneQuanLyNVAtPosition(position));
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        position--;
        if (position <= 0) {
            position = 0;
        }

        setModel(dao.getOneQuanLyNVAtPosition(position));
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        position++;
        if (position >= dao.count()) {
            position = dao.count() - 1;
        }
        setModel(dao.getOneQuanLyNVAtPosition(position));

    }//GEN-LAST:event_btnNextActionPerformed

    private void tabbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbangMouseClicked
        // TODO add your handling code here:
        int point =tabbang.rowAtPoint(evt.getPoint());
        QuanLyNV nv = dao.getOneQuanLyNVAtPosition(point);
        setModel(nv);
    }//GEN-LAST:event_tabbangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrQuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrQuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrQuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrQuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrQuanLyNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrist;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboPhongban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tabbang;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables
}
