/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java3;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trany
 */
public class SinhVienJF extends javax.swing.JFrame {

    SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    public static SinhVienDAO dao = new SinhVienDAO();
    String strHinhanh = null;

    /**
     * Creates new form NhanVienJF
     */
    public SinhVienJF() {
        initComponents();
        setLocationRelativeTo(null);
        filldata();
    }
//khu code
    //Hàm reset()

    public void reset() {
        txtmasinhvien.setText("");
        txttenSV.setText("");
        txtdate.setText("");
        rdnam.setSelected(true);
        txtdiachi.setText("");
        lblhinhanh.setText("HINH ANH");
        lblhinhanh.setIcon(null);
        strHinhanh = null;

    }

    public SinhVien getModel() throws ParseException {
        SinhVien s = new SinhVien();
        s.setTenNV(txttenSV.getText());
        s.setMaSV(txtmasinhvien.getText());
        s.setNgaySinh(date.parse(txtdate.getText()));
        boolean gt = false;
        if (rdnam.isSelected()) {
            gt = true;//nam
        }
        s.setGioiTinh(gt);
        s.setDiaChi(txtdiachi.getText());
        if (strHinhanh == null) {
            s.setHinhAnh("NO AVATA ");
        } else {
            s.setHinhAnh(strHinhanh);
        }
        return s;
    }

    public boolean valicheckDate() {
        if (txtmasinhvien.getText().isEmpty()
                || txttenSV.getText().isEmpty()
                || txtdate.getText().isEmpty()
                || txtdiachi.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    //ham set
    public void setModel(SinhVien sv) {
        int rowdata = tabbang.getSelectedRow();
        txtmasinhvien.setText(sv.getMaSV());
        txttenSV.setText(sv.getTenNV());
        txtdate.setText(date.format(sv.getNgaySinh()));
        rdnam.setSelected(sv.isGioiTinh());
        rdnu.setSelected(!sv.isGioiTinh());
        txtdiachi.setText(sv.getDiaChi());
        if (sv.getHinhAnh().equalsIgnoreCase("NO AVATA")) {
            lblhinhanh.setText("NO AVATA");
            lblhinhanh.setIcon(null);
        } else {
            lblhinhanh.setText("");
            ImageIcon micon = new ImageIcon(getClass().getResource("/Images/" + tabbang.getValueAt(rowdata, 5).toString()));
            Image img = micon.getImage();
            img.getScaledInstance(lblhinhanh.getWidth(), lblhinhanh.getY(), 0);
            lblhinhanh.setIcon(micon);
        }
    }

    //ham do table 
    public void filldata() {
        DefaultTableModel tbmodel = (DefaultTableModel) tabbang.getModel();
        tbmodel.setRowCount(0);// ham xoa
        for (SinhVien s : dao.getAllSinhVien()) {
            Object rowdata[] = new Object[6];
            rowdata[0] = s.getMaSV();
            rowdata[1] = s.getTenNV();
            rowdata[2] = date.format(s.getNgaySinh());
            String gt = "Nữ";
            if (s.isGioiTinh()) {
                gt = "Nam";
            }
            rowdata[3] = gt;
            rowdata[4] = s.getDiaChi();
            rowdata[5] = s.getHinhAnh();
            tbmodel.addRow(rowdata);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnadd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        txtmasinhvien = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        txttenSV = new javax.swing.JTextField();
        btnxoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabbang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rdnam = new javax.swing.JRadioButton();
        btnexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdnu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        lblhinhanh = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        lblstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnadd.setText("THEM MOI");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel7.setText("DIA CHI:");

        btnsave.setText("LUU LAI");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setText("SUA");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnxoa.setText("XOA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        tabbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MA SINH VIEN", "TEN SINH VIEN", "NGAY SINH", "GIOI TINH", "DIA CHI", "HINH ANH"
            }
        ));
        tabbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabbang);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("QUAN LI SINH VIEN");

        buttonGroup1.add(rdnam);
        rdnam.setText("NAM");

        btnexit.setText("THOAT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel2.setText("MA SINH VIEN:");

        buttonGroup1.add(rdnu);
        rdnu.setText("NU");

        jLabel3.setText("TEN SINH VIEN:");

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        lblhinhanh.setText("HINH ANH");
        lblhinhanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblhinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhinhanhMouseClicked(evt);
            }
        });

        jLabel6.setText("GIOI TINH:");

        jLabel4.setText("NGAY SINH:");

        lblstatus.setText("STATUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdnam)
                                .addGap(75, 75, 75)
                                .addComponent(rdnu))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd)
                            .addComponent(btnedit))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnxoa)
                            .addComponent(btnsave))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblstatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnexit)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txttenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(rdnam)
                                    .addComponent(rdnu))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnadd)
                                    .addComponent(btnsave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnedit)
                                    .addComponent(btnxoa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnexit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblstatus)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (valicheckDate()) {
            try {
                SinhVien s = getModel();
                if (dao.add(s) > 0) {
                    JOptionPane.showMessageDialog(this, "BAN LUU KHONG DUNG");
                    lblstatus.setText("BAN LUU KHONG DUNG");
                    lblstatus.setForeground(Color.red);
                } else {
                    JOptionPane.showMessageDialog(this, "BAN LUU THANH CONG");
                    lblstatus.setText("BAN LUU THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    filldata();
                }
            } catch (ParseException ex) {
                System.out.println("Error:" + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP GIA TRI");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:

        if (txtmasinhvien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP GIA TRI VAO DE EDIT");
        } else {
            try {
                SinhVien s = getModel();
                if (dao.edit(s) < 0) {
                    JOptionPane.showMessageDialog(this, "BAN AN OKE DE CAP NHAT");
                    lblstatus.setText("BAN DANG CAP NHAT THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    filldata();
                } else {
                    JOptionPane.showMessageDialog(this, "BAN EDIT THAT BAI");
                    lblstatus.setText("BAN KHONG TIM THAY");
                    lblstatus.setForeground(Color.red);
                }
            } catch (Exception ex) {
                System.out.println("Error:" + ex.toString());;
            }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmasinhvien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP DAY DU");
        } else {
            try {
                SinhVien s = getModel();
                if (dao.del(s) < 0) {
                    JOptionPane.showMessageDialog(this, "VUI LONG CHON ẤN OKE DE TIEP TUC XOA");
                    JOptionPane.showMessageDialog(this, "BAN DA XOA THANH CONG");
                    lblstatus.setText("BAN DA XOA THANH CONG");
                    lblstatus.setForeground(Color.blue);
                    filldata();
                } else {
                    lblstatus.setText("KHONG TIM THAY YEU CAU CUA BAN");
                    lblstatus.setForeground(Color.red);
                }
            } catch (Exception e) {
                System.out.println("Erorr:" + e.toString());
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tabbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbangMouseClicked
        // TODO add your handling code here:
        int point = tabbang.rowAtPoint(evt.getPoint());
        String maSv = tabbang.getValueAt(point, 0).toString();
        SinhVien sv = dao.getNhanVienByID(maSv);
        if (sv == null) {
            return;
        }
        try {
            setModel(sv);
        } catch (Exception e) {
            System.out.println("No AVATA");
        }
    }//GEN-LAST:event_tabbangMouseClicked

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void lblhinhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhinhanhMouseClicked
        try {
            // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser("D:\\Users\\trany\\Documents\\NetBeansProjects\\Menu\\build\\classes\\Images");
            fileChooser.showOpenDialog(null);
            File file = fileChooser.getSelectedFile();
            Image img = ImageIO.read(file);
//            ImageIcon icon = new ImageIcon(img.getScaledInstance(lblhinhanh.getWidth(), lblhinhanh.getHeight(), 0));
            lblhinhanh.setText("");
            strHinhanh = file.getName();
            int width = lblhinhanh.getWidth();
            int height = lblhinhanh.getHeight();
            lblhinhanh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));

        } catch (IOException ex) {
            Logger.getLogger(SinhVienJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblhinhanhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblhinhanh;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JTable tabbang;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtmasinhvien;
    private javax.swing.JTextField txttenSV;
    // End of variables declaration//GEN-END:variables
}
