/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SinhVien;

import Datautiles.DateHelps;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SinhVienDiaLog extends javax.swing.JDialog {
    SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
    ChuyenNganhDAO dao = new ChuyenNganhDAO();
    SinhVienDAO daos = new SinhVienDAO();

    /**
     * Creates new form SinhVienDiaLog
     */
    public SinhVienDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getDataCombobox();
        setLocationRelativeTo(null);
        filldata();
    }

    public void getDataCombobox() {
        DefaultComboBoxModel<ChuyenNganh> model = (DefaultComboBoxModel) cbomacn.getModel();
        for (ChuyenNganh cn : dao.getAllChuyenNganh()) {
            model.addElement(cn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabbang = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        rdnam = new javax.swing.JRadioButton();
        rdnu = new javax.swing.JRadioButton();
        txtmasv = new javax.swing.JTextField();
        txttensv = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbomacn = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("QUAN LY");

        jLabel2.setText("MA SV:");

        jLabel3.setText("TEN SV:");

        jLabel4.setText("NGAY SINH:");

        jLabel5.setText("GIOI TINH:");

        jLabel6.setText("PHONE:");

        tabbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MA SV", "TEN SV", "MA CN", "NGAY SINH", "GIOI TINH", "PHONE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabbang);
        if (tabbang.getColumnModel().getColumnCount() > 0) {
            tabbang.getColumnModel().getColumn(0).setResizable(false);
        }

        btnadd.setText("THEM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnam);
        rdnam.setText("NAM");

        buttonGroup1.add(rdnu);
        rdnu.setText("NU");

        btnsua.setText("SUA");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnmoi.setText("MOI");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnxoa.setText("XOA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jButton5.setText("THOAT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("MA CN:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdnam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdnu))
                                    .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txttensv, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtmasv)
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(cbomacn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnadd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmoi)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbomacn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdnam)
                    .addComponent(rdnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnmoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void reset() {
        txtmasv.setText("");
        txtngaysinh.setText("");
        txtphone.setText("");
        txttensv.setText("");
        cbomacn.setSelectedIndex(0);
        rdnam.setText("");
        rdnu.setText("");

    }

    public SinhVien getModel() {
        SinhVien sv = new SinhVien();
        sv.setMaSV(Integer.parseInt(txtmasv.getText()));
        sv.setTenSV(txttensv.getText());
        ChuyenNganh n = (ChuyenNganh) cbomacn.getSelectedItem();
        sv.setMaCN(n);
        sv.setNgaySinh(DateHelps.toDate(txtngaysinh.getText()));
        boolean gt = false;
        if (rdnam.isSelected()) {
            gt = true;
        }
        sv.setGioiTinh(gt);
        sv.setPhone(txtphone.getText());
        return sv;
    }

    public void filldata() {
        DefaultTableModel model = (DefaultTableModel) tabbang.getModel();
        model.setRowCount(0);
        for (SinhVien sv : daos.getAllSinhVien()) {
            Object rowdata[] = new Object[6];
            rowdata[0] = sv.getMaSV();
            rowdata[1] = sv.getTenSV();
            int p = dao.findnhan(sv.getMaCN().getMaCN());
            rowdata[2] = dao.getAllChuyenNganh().get(p).getMaCN();;
            rowdata[3] = DateHelps.toString(sv.getNgaySinh());
            String gt = "Nữ";
            if (sv.isGioiTinh()) {
                gt = "Nam";
            }
            rowdata[4] = gt;
            rowdata[5] = sv.getPhone();
            model.addRow(rowdata);
        }
    }
    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if (txtmasv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "yeu cau ban nhap day du");
        } else {
            SinhVien sv = getModel();
            if (daos.add(sv) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "banthem thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "ban them that bai");
            }
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtmasv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "yeu cau ban nhap day du");
        } else {
            SinhVien sv = getModel();
            if (daos.edit(sv) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "ban edit thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "ban edit that bai");
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmasv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "yeu cau ban nhap day du");
        } else {
            SinhVien sv = getModel();
            if (daos.dell(sv) > 0) {
                filldata();
                JOptionPane.showMessageDialog(this, "ban dell thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "ban dell that bai");
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed
    public void setModel(SinhVien ql) {
        txtmasv.setText(Integer.toString(ql.getMaSV()));
        txttensv.setText((ql.getTenSV()));
        cbomacn.setSelectedItem(ql.getMaCN());
        txtngaysinh.setText(DateHelps.toString(ql.getNgaySinh()));
        txtphone.setText(ql.getPhone());
        rdnam.setSelected(ql.isGioiTinh());
        rdnu.setSelected(!ql.isGioiTinh());
//      
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbangMouseClicked
        // TODO add your handling code here:
        SinhVien sv = new SinhVien();
        int position = tabbang.rowAtPoint(evt.getPoint());
        txtmasv.setText(tabbang.getValueAt(position, 0).toString());
        txttensv.setText(tabbang.getValueAt(position, 1).toString());
//        int p = dao.findnhan(tabbang.getValueAt(position, 2).toString());
        cbomacn.setSelectedIndex(dao.findnhan(Integer.parseInt(tabbang.getValueAt(position, 2).toString())));
        if (tabbang.getValueAt(position, 4).equals(false)) {
            rdnam.setSelected(true);
            rdnu.setSelected(false);
        } else {
            rdnam.setSelected(false);
            rdnu.setSelected(true);
        }
        txtngaysinh.setText(tabbang.getValueAt(position, 3).toString());
        txtphone.setText(tabbang.getValueAt(position, 5).toString());

    }//GEN-LAST:event_tabbangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SinhVienDiaLog dialog = new SinhVienDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbomacn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JTable tabbang;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txttensv;
    // End of variables declaration//GEN-END:variables
}
