/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanlyNhanVien;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trany
 */
public class JfNvQuanTri extends javax.swing.JFrame {

    NhanVienDAO daonv = new NhanVienDAO();
    static int id = 0;

    /**
     * Creates new form JfNvQuanTri
     */
    public JfNvQuanTri() {
        initComponents();
        setLocationRelativeTo(null);
        filldata();
    }
//khu code chính
    //hàm reset()

    public void reset() {
        txtmaNV.setText("");
        txtmatkhau.setText("");
        txtxacnhanmk.setText("");
        txthovaten.setText("");
        rdnhanvien.setSelected(true);
    }

    //hàm thêm
    //1/getModel
    public NhanVien getModeL() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtmaNV.getText());
        nv.setMatKhau(txtmatkhau.getText());
        nv.setHoTen(txthovaten.getText());
        boolean cv = false;
        if (rdnhanvien.isSelected()) {
            cv = true;
        }
        nv.setVaitro(cv);
        if (txtmatkhau.getText().equals(txtxacnhanmk.getText())) {
            return nv;
        }
        return null;
    }

    public boolean checkValiData() {
        if (txtmaNV.getText().isEmpty()
                || txtmatkhau.getText().isEmpty()
                || txtxacnhanmk.getText().isEmpty()
                || txthovaten.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    //ham filldata
    public void filldata() {
        DefaultTableModel model = (DefaultTableModel) tabbangnhanvien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : daonv.getAllNhanVien()) {
            Object rowdata[] = new Object[4];
            rowdata[0] = nv.getMaNV();
            rowdata[1] = nv.getMatKhau();
            rowdata[2] = nv.getHoTen();
            String cv = "Trưởng Phòng";
            if (nv.isVaitro()) {
                cv = "Nhân Viên";
            }
            rowdata[3] = cv;
            model.addRow(rowdata);
        }
    }

    //hàm set()
    public void setModel(NhanVien nv) {
        txtmaNV.setText(nv.getMaNV());
        txtmatkhau.setText(nv.getMatKhau());
        txthovaten.setText(nv.getHoTen());
        rdnhanvien.setSelected(nv.isVaitro());
        rdtruongphong.setSelected(!nv.isVaitro());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdnhanvien = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        txtmaNV = new javax.swing.JTextField();
        btnmoi = new javax.swing.JButton();
        btnFrist = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        txthovaten = new javax.swing.JTextField();
        btnLast = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rdtruongphong = new javax.swing.JRadioButton();
        txtmatkhau = new javax.swing.JPasswordField();
        txtxacnhanmk = new javax.swing.JPasswordField();
        btnThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabbangnhanvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản lý Nhân viên Quản Trị");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        buttonGroup1.add(rdnhanvien);
        rdnhanvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdnhanvien.setSelected(true);
        rdnhanvien.setText("Nhân viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Họ và tên");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Xác nhận mật khẩu");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnFrist.setText("|<");
        btnFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFristActionPerformed(evt);
            }
        });

        btnback.setText("<<");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnnext.setText(">>");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vai trò");

        buttonGroup1.add(rdtruongphong);
        rdtruongphong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdtruongphong.setText("Trưởng phòng");

        btnThoat.setText("THOAT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txthovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnthem)
                                .addGap(18, 18, 18)
                                .addComponent(btnsua)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnmoi)
                                .addGap(140, 140, 140)
                                .addComponent(btnFrist)
                                .addGap(18, 18, 18)
                                .addComponent(btnback)
                                .addGap(18, 18, 18)
                                .addComponent(btnnext)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtmatkhau, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtmaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
                            .addComponent(txtxacnhanmk)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(rdtruongphong)
                        .addGap(103, 103, 103)
                        .addComponent(rdnhanvien)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(txtxacnhanmk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txthovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdtruongphong)
                    .addComponent(rdnhanvien))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnmoi)
                    .addComponent(btnFrist)
                    .addComponent(btnback)
                    .addComponent(btnnext)
                    .addComponent(btnLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        tab.addTab("CẬP NHẬT", jPanel1);

        tabbangnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NV", "MẬT KHẨU", "HỌ VÀ TÊN", "VAI TRÒ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabbangnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbangnhanvienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabbangnhanvienMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabbangnhanvien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (checkValiData()) {
            try {
                NhanVien nv = getModeL();
                if (daonv.add(nv) > 0) {
                    JOptionPane.showMessageDialog(this, "BẠN THÊM THÀNH CÔNG");
                    filldata();
                } else {
                    JOptionPane.showMessageDialog(this, "BẠN THÊM KHÔNG THÀNH CÔNG");
                }

            } catch (Exception e) {
                System.out.println("Error:" + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "BAN CHUA NHAP DAY DU THEM OVER");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtmaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BẠN CHƯA CẬP NHẬT MÃ NHÂN VIÊN");
        } else {
            try {
                NhanVien nv = getModeL();
                if (daonv.edit(nv) > 0) {
                    JOptionPane.showMessageDialog(this, "BẠN ĐÃ CẬP NHẬT THÀNH CÔNG");
                    filldata();
                } else {
                    JOptionPane.showMessageDialog(this, "CẬP NHẬT THẤT BẠI");
                }
            } catch (Exception e) {
                System.out.println("Error:" + e.toString());
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "BẠN CHƯA CẬP NHẬT MÃ NHÂN VIÊN ĐỂ XÓA");
        } else {
            try {
                NhanVien nv = getModeL();
                if (daonv.dell(nv) > 0) {
                    JOptionPane.showMessageDialog(this, "BẠN ĐÃ XÓA THÀNH CÔNG");
                    filldata();
                } else {
                    JOptionPane.showMessageDialog(this, "KHÔNG TÌM THẤY MÃ ID NHÂN VIÊN ĐỂ XÓA");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnmoiActionPerformed
    public NhanVien getNhanVienAtPosition(int pos) {
        NhanVien nv = new NhanVien();
        nv.setMaNV(tabbangnhanvien.getValueAt(pos, 0).toString());
        nv.setMatKhau(tabbangnhanvien.getValueAt(pos, 1).toString());
        nv.setHoTen(tabbangnhanvien.getValueAt(pos, 2).toString());
        nv.setVaitro(tabbangnhanvien.getValueAt(pos, 3).toString().equalsIgnoreCase("Nhân Viên"));
        return nv;
    }
    private void btnFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFristActionPerformed
        // TODO add your handling code here:
        id = 0;
        NhanVien nv = getNhanVienAtPosition(id);
        setModel(nv);

    }//GEN-LAST:event_btnFristActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        id--;
        if (id <= 0) {
            id = 0;
        }
        NhanVien nv = getNhanVienAtPosition(id);
        setModel(nv);

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        id++;
        if (id >= daonv.getAllNhanVien().size()-1) {
            id = daonv.getAllNhanVien().size()-1;
        }
        NhanVien nv = getNhanVienAtPosition(id);
        setModel(nv);
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        id = daonv.getAllNhanVien().size() - 1;
        NhanVien nv = getNhanVienAtPosition(id);
        setModel(nv);

    }//GEN-LAST:event_btnLastActionPerformed

    private void tabbangnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbangnhanvienMouseClicked
        // TODO add your handling code here:
       
        int id = tabbangnhanvien.rowAtPoint(evt.getPoint());
        txtmaNV.setText(tabbangnhanvien.getValueAt(id, 0).toString());
        txtmatkhau.setText(tabbangnhanvien.getValueAt(id, 1).toString());
        txtxacnhanmk.setText(tabbangnhanvien.getValueAt(id, 1).toString());

        txthovaten.setText(tabbangnhanvien.getValueAt(id, 2).toString());
        if (tabbangnhanvien.getValueAt(id, 3).toString().equalsIgnoreCase("Trưởng Phòng")) {
            rdtruongphong.setSelected(true);
        } else {
            rdnhanvien.setSelected(true);
        }


    }//GEN-LAST:event_tabbangnhanvienMouseClicked

    private void tabbangnhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbangnhanvienMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            tab.setSelectedIndex(0);
           
           int id = tabbangnhanvien.rowAtPoint(evt.getPoint());
            String maNV = tabbangnhanvien.getValueAt(id, 1).toString();
        }
    }//GEN-LAST:event_tabbangnhanvienMousePressed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfNvQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfNvQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfNvQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfNvQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfNvQuanTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrist;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdnhanvien;
    private javax.swing.JRadioButton rdtruongphong;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tabbangnhanvien;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JPasswordField txtxacnhanmk;
    // End of variables declaration//GEN-END:variables
}
