/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hoadon;

import KhachHang.KhachHang;
import KhachHang.KhachHangDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class HoaDonDiaLog extends javax.swing.JDialog {

    static int id = 0;
    HoaDonDAO dao = new HoaDonDAO();
    KhachHangDAO daokh = new KhachHangDAO();
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form HoaDonDiaLog
     */
    public HoaDonDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        filldata();
    }
    
    public void getDataCombobox() {
        DefaultComboBoxModel<KhachHang> model = (DefaultComboBoxModel) cbomakh.getModel();
        for (KhachHang kh : daokh.getAllKhachHang()) {
            model.addElement(kh);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        txtngaymuahang = new javax.swing.JTextField();
        cbomakh = new javax.swing.JComboBox<>();
        txttrangthai = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLISTT = new javax.swing.JTable();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("HOA DON");

        jLabel2.setText("MÃ HÓA ĐƠN");

        jLabel3.setText("NGÀY MUA HÀNG");

        jLabel4.setText("MÃ KHÁCH HÀNG");

        jLabel5.setText("TRẠNG THÁI");

        cbomakh.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbomakhPopupMenuWillBecomeVisible(evt);
            }
        });

        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("SỬA");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("XÓA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnmoi.setText("MỚI");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnthoat.setText("EXIT");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        TABLISTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ HÓA ĐƠN", "NGÀY MUA HÀNG", "MÃ KHÁCH HÀNG", "TRẠNG THÁI"
            }
        ));
        TABLISTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLISTTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TABLISTTMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TABLISTT);

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(">|");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtngaymuahang, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(txtmahoadon)
                                .addComponent(txttrangthai, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(cbomakh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnthem)
                                    .addComponent(btnxoa))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnsua)
                                    .addComponent(btnmoi))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFirst)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBack))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNext)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLast)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addGap(391, 391, 391))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtngaymuahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbomakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnFirst)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(btnmoi)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthoat))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public HoaDon getModel() throws ParseException {
        HoaDon hd = new HoaDon();
        KhachHang kh = (KhachHang) cbomakh.getSelectedItem();
        hd.setMaKhachHang(kh.getMaKhacHang());
        hd.setMaHoaDon((txtmahoadon.getText()));
        hd.setTrangThai(txttrangthai.getText());
        hd.setNgayMuaHang(date_format.parse(txtngaymuahang.getText()));
        return hd;
    }
    
    public boolean CheckValidata() {
        if (txtmahoadon.getText().isEmpty() || txtngaymuahang.getText().isEmpty() || txttrangthai.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
    public void filldata() {
        DefaultTableModel model = (DefaultTableModel) TABLISTT.getModel();
        model.setRowCount(0);
        for (HoaDon hd : dao.getAllHoaDon()) {
            Object rowdata[] = new Object[4];
            rowdata[0] = hd.getMaHoaDon();
            rowdata[1] = date_format.format(hd.getNgayMuaHang());
            rowdata[2] = hd.getMaKhachHang();
            rowdata[3] = hd.getTrangThai();
            model.addRow(rowdata);
        }
        
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (CheckValidata()) {
            try {
                HoaDon hd = getModel();
                if (dao.add(hd) > 0) {
                    filldata();
                    JOptionPane.showMessageDialog(this, "Bạn thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn thêm thất bại");
                }
            } catch (ParseException ex) {
                Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Ban chưa nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtmahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập lại đúng");
        } else {
            try {
                HoaDon hd = getModel();
                if (dao.edit(hd) > 0) {
                    filldata();
                    JOptionPane.showMessageDialog(this, "Bạn mới update thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn mới update thất bại");
                }
            } catch (ParseException ex) {
                Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed
    public void setModel(HoaDon hd) {
        txttrangthai.setText(hd.getTrangThai());
        txtngaymuahang.setText(date_format.format(hd.getNgayMuaHang()));
        txtmahoadon.setText((hd.getMaHoaDon()));
        cbomakh.setSelectedItem(hd.getMaKhachHang());
    }
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmahoadon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập lại đúng");
        } else {
            try {
                HoaDon hd = getModel();
                if (dao.dell(hd) > 0) {
                    filldata();
                    JOptionPane.showMessageDialog(this, "Bạn mới xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn mới xóa thất bại");
                }
            } catch (ParseException ex) {
                Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnxoaActionPerformed
    public void reset() {
        txtmahoadon.setText("");
        txtngaymuahang.setText("");
        txttrangthai.setText("");
        cbomakh.setSelectedIndex(0);
    }
    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void TABLISTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLISTTMouseClicked
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        int position = TABLISTT.rowAtPoint(evt.getPoint());
        txtmahoadon.setText(TABLISTT.getValueAt(position, 0).toString());
        txtngaymuahang.setText(TABLISTT.getValueAt(position, 1).toString());
        cbomakh.setSelectedIndex(daokh.findKhachhang(TABLISTT.getValueAt(position, 2).toString()));
        txttrangthai.setText(TABLISTT.getValueAt(position, 3).toString());
        
    }//GEN-LAST:event_TABLISTTMouseClicked

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void TABLISTTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLISTTMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int rowID = TABLISTT.rowAtPoint(evt.getPoint());
            txtmahoadon.setText(TABLISTT.getValueAt(rowID, 0).toString());
            txtngaymuahang.setText(TABLISTT.getValueAt(rowID, 1).toString());
//        cbomakh.setSelectedIndex(daokh.findKhachhang(TABLISTT.getValueAt(rowID, 2).toString()));
            txttrangthai.setText(TABLISTT.getValueAt(rowID, 3).toString());
        }
    }//GEN-LAST:event_TABLISTTMousePressed
    public HoaDon getHoaDonNHAtPosition(int pos) throws ParseException {
        HoaDon hd = new HoaDon();
        hd.setMaHoaDon((TABLISTT.getValueAt(pos, 0).toString()));
        hd.setNgayMuaHang(date_format.parse(TABLISTT.getValueAt(pos, 1).toString()));
        KhachHang kh = (KhachHang) cbomakh.getSelectedItem();
        hd.setMaKhachHang(kh.getMaKhacHang());
        cbomakh.setSelectedIndex(daokh.findKhachhang(TABLISTT.getValueAt(pos, 2).toString()));
        hd.setTrangThai(TABLISTT.getValueAt(pos, 3).toString());
        return hd;
    }
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            // TODO add your handling code here:
            id = 0;
            HoaDon hd = getHoaDonNHAtPosition(id);
            setModel(hd);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            // TODO add your handling code here:
            id--;
            if (id <= 0) {
                id = 0;
            }
            HoaDon hd = getHoaDonNHAtPosition(id);
            setModel(hd);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            // TODO add your handling code here:
            id++;
            if (id >= dao.getAllHoaDon().size() - 1) {
                id = dao.getAllHoaDon().size() - 1;
            }
            HoaDon hd = getHoaDonNHAtPosition(id);
            setModel(hd);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            // TODO add your handling code here:
            id = dao.getAllHoaDon().size() - 1;
            HoaDon hd = getHoaDonNHAtPosition(id);
            setModel(hd);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonDiaLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void cbomakhPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbomakhPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        getDataCombobox();
    }//GEN-LAST:event_cbomakhPopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonDiaLog dialog = new HoaDonDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLISTT;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbomakh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtngaymuahang;
    private javax.swing.JTextField txttrangthai;
    // End of variables declaration//GEN-END:variables
}
