package models;
// Generated May 3, 2020 9:13:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departs generated by hbm2java
 */
@Entity
@Table(name="departs"
    ,schema="dbo"
    ,catalog="dbDemo"
)
public class Departs  implements java.io.Serializable {


     private String id;
     private String name;
     private Set<Staffs> staffses = new HashSet<Staffs>(0);

    public Departs() {
    }

	
    public Departs(String id) {
        this.id = id;
    }
    public Departs(String id, String name, Set<Staffs> staffses) {
       this.id = id;
       this.name = name;
       this.staffses = staffses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departs")
    public Set<Staffs> getStaffses() {
        return this.staffses;
    }
    
    public void setStaffses(Set<Staffs> staffses) {
        this.staffses = staffses;
    }




}


