package models;
// Generated May 3, 2020 9:13:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name="staffs"
    ,schema="dbo"
    ,catalog="dbDemo"
)
public class Staffs  implements java.io.Serializable {


     private String id;
     private Departs departs;
     private Date birthday;
     private String email;
     private boolean gender;
     private String name;
     private String notes;
     private String phone;
     private String photo;
     private double salary;

    public Staffs() {
    }

	
    public Staffs(String id, boolean gender, double salary) {
        this.id = id;
        this.gender = gender;
        this.salary = salary;
    }
    public Staffs(String id, Departs departs, Date birthday, String email, boolean gender, String name, String notes, String phone, String photo, double salary) {
       this.id = id;
       this.departs = departs;
       this.birthday = birthday;
       this.email = email;
       this.gender = gender;
       this.name = name;
       this.notes = notes;
       this.phone = phone;
       this.photo = photo;
       this.salary = salary;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="depart_id")
    public Departs getDeparts() {
        return this.departs;
    }
    
    public void setDeparts(Departs departs) {
        this.departs = departs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="gender", nullable=false)
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="name", length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="notes", length=500)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="phone", length=12)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="photo", length=500)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="salary", nullable=false, precision=53, scale=0)
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }




}


