package models;
// Generated Mar 12, 2020 1:48:52 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departs generated by hbm2java
 */
@Entity
@Table(name="Departs"
    ,schema="dbo"
    ,catalog="demobaitap04"
)
public class Departs  implements Serializable {


     private String id;
     private String name;

    public Departs() {
    }

	
    public Departs(String id) {
        this.id = id;
    }
    public Departs(String id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


